"""
Batch Pipeline Validation CLI for Finance/Month-End

This module provides a batch validation runner for pipeline validation,
intended for finance month-end checks. It reuses validate_pipeline()
without modifying any chat behavior.

Usage:
  # By numeric range (e.g., 0752-0760)
  bench --site <site> execute raven_ai_agent.cli.batch_pipeline_validation.run_batch_validation

  # With explicit IDs via environment variable
  RAVEN_BATCH_IDS="0752,0753,SAL-QTN-2024-00763" bench --site <site> execute raven_ai_agent.cli.batch_pipeline_validation.run_batch_validation
"""
from __future__ import annotations

import calendar
import os
from datetime import date, datetime
from pathlib import Path
from typing import Iterable

import frappe

from raven_ai_agent.api.truth_hierarchy import validate_pipeline


def expand_range(prefix: str, start: int, end: int) -> list[str]:
    """
    Expand a numeric range into a list of IDs.
    
    Args:
        prefix: Prefix for the IDs (e.g., "" for numeric, "SAL-QTN-2024-" for full names)
        start: Start number (inclusive)
        end: End number (inclusive)
    
    Returns:
        List of IDs like ["0752", "0753", ...] or ["SAL-QTN-2024-0752", ...]
    """
    return [f"{prefix}{i:04d}" for i in range(start, end + 1)]


def _normalize_ids(raw_ids: Iterable[str]) -> list[str]:
    """Normalize a list of raw ID strings."""
    return [i.strip() for i in raw_ids if i and i.strip()]


def _get_ids_from_env() -> list[str]:
    """
    Get IDs from environment variable RAVEN_BATCH_IDS (comma-separated)
    or RAVEN_BATCH_RANGE (e.g., "752-760" for numeric range).
    """
    # Check for explicit IDs
    ids_env = os.environ.get("RAVEN_BATCH_IDS", "").strip()
    if ids_env:
        return _normalize_ids(ids_env.split(","))
    
    # Check for range
    range_env = os.environ.get("RAVEN_BATCH_RANGE", "").strip()
    if range_env:
        try:
            if "-" in range_env:
                start, end = map(int, range_env.split("-"))
                return expand_range("", start, end)
            else:
                # Single number
                return [f"{int(range_env):04d}"]
        except ValueError:
            pass
    
    return []


def run_batch_validation(raw_ids: Iterable[str] | None = None) -> dict:
    """
    Batch runner for pipeline validation, intended for finance month-end.

    Usage from bench:
      # By range (default: 752-760)
      bench --site <site> execute raven_ai_agent.cli.batch_pipeline_validation.run_batch_validation
      
      # With explicit IDs
      RAVEN_BATCH_IDS="0752,0753,SAL-QTN-2024-00763" bench --site <site> execute raven_ai_agent.cli.batch_pipeline_validation.run_batch_validation
      
      # With numeric range
      RAVEN_BATCH_RANGE="752-765" bench --site <site> execute raven_ai_agent.cli.batch_pipeline_validation.run_batch_validation

    Args:
        raw_ids: Optional list of Quotation/SO IDs to validate.
                 If None, reads from RAVEN_BATCH_IDS or RAVEN_BATCH_RANGE env vars.

    Returns:
        Dict with ids processed and output file paths.
    """
    # Get IDs from env if not provided
    if raw_ids is None:
        raw_ids = _get_ids_from_env()
    
    # Default to range 752-760 if still empty
    if not raw_ids:
        raw_ids = expand_range("", 752, 760)
    
    ids = _normalize_ids(raw_ids)

    app_path = Path(frappe.get_app_path("raven_ai_agent"))
    out_dir = app_path / "transcripts"
    out_dir.mkdir(exist_ok=True)

    ts = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    json_path = out_dir / f"batch_pipeline_{ts}.json"
    md_path = out_dir / f"batch_pipeline_{ts}.md"

    records: list[dict] = []
    md_lines: list[str] = []

    md_lines.append(f"# Batch Pipeline Validation ({ts})")
    md_lines.append("")
    md_lines.append("This report was generated by Raven batch pipeline validation.")
    md_lines.append("")
    md_lines.append("## Summary")
    md_lines.append("")
    md_lines.append(f"- Total IDs processed: {len(ids)}")
    md_lines.append(f"- IDs: {', '.join(ids)}")
    md_lines.append("")

    for raw_id in ids:
        try:
            result = validate_pipeline(raw_id)
            status = "ok"
            error = None
        except Exception as exc:
            # We still want the batch to continue if one ID fails
            result = f"ERROR: {exc}"
            status = "error"
            error = str(exc)

        rec = {
            "input": raw_id,
            "status": status,
            "error": error,
            "output": result,
        }
        records.append(rec)

        md_lines.append(f"## {raw_id}")
        md_lines.append("")
        md_lines.append(result if isinstance(result, str) else str(result))
        md_lines.append("")
        md_lines.append("---")
        md_lines.append("")

    # Write output files
    json_path.write_text(frappe.as_json(records, indent=2), encoding="utf-8")
    md_path.write_text("\n".join(md_lines), encoding="utf-8")

    print(f"Wrote JSON batch report to: {json_path}")
    print(f"Wrote Markdown batch report to: {md_path}")

    return {
        "ids": ids,
        "json_path": str(json_path),
        "md_path": str(md_path),
    }


def main():
    """Entry point for bench execute."""
    return run_batch_validation()


def _is_last_day_of_month(today: date | None = None) -> bool:
    """Check if today is the last day of the month."""
    today = today or date.today()
    last_day = calendar.monthrange(today.year, today.month)[1]
    return today.day == last_day


def run_month_end_batch():
    """
    Entry point for Frappe scheduler.
    
    Runs daily at 23:30 via cron (defined in hooks.py).
    Only executes batch validation on the last day of the month.
    
    Uses same env vars as CLI:
      - RAVEN_BATCH_IDS
      - RAVEN_BATCH_RANGE
    
    Returns:
        Dict with ids processed and output file paths, or None if skipped.
    """
    if not _is_last_day_of_month():
        frappe.logger().info("raven_ai_agent: month-end batch skipped (not last day)")
        return None

    frappe.logger().info("raven_ai_agent: starting month-end batch validation")
    res = run_batch_validation()
    
    frappe.logger().info(
        "raven_ai_agent: month-end batch complete ids=%s md=%s",
        res.get("ids"),
        res.get("md_path"),
    )
    
    # Optionally symlink latest report to sites folder for easy access
    _symlink_latest_report(res.get("md_path"), res.get("json_path"))
    
    return res


def _symlink_latest_report(md_path: str | None, json_path: str | None):
    """Create symlinks to latest report in sites folder for easy access."""
    if not md_path or not json_path:
        return
    
    try:
        site_path = Path(frappe.get_site_path())
        reports_dir = site_path / "private" / "files" / "raven_reports"
        reports_dir.mkdir(parents=True, exist_ok=True)
        
        # Symlink latest files
        latest_md = reports_dir / "latest_batch.md"
        latest_json = reports_dir / "latest_batch.json"
        
        if latest_md.exists():
            latest_md.unlink()
        if latest_json.exists():
            latest_json.unlink()
            
        Path(md_path).symlink_to(latest_md)
        Path(json_path).symlink_to(latest_json)
        
        frappe.logger().info("raven_ai_agent: symlinked reports to %s", reports_dir)
    except Exception as e:
        frappe.logger().warning("raven_ai_agent: failed to create symlinks: %s", e)


if __name__ == "__main__":
    main()
