"""
Batch Pipeline Validation CLI for Finance/Month-End

This module provides a batch validation runner for pipeline validation,
intended for finance month-end checks. It reuses validate_pipeline()
without modifying any chat behavior.
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Iterable

import frappe

from raven_ai_agent.api.truth_hierarchy import validate_pipeline


# Default IDs to validate - finance can customize this list
DEFAULT_IDS = [
    "0752",
    "0753",
    "0754",
    "0755",
    "SAL-QTN-2024-00752",
    "SAL-QTN-2024-00763",
]


def expand_range(prefix: str, start: int, end: int) -> list[str]:
    """
    Expand a numeric range into a list of IDs.
    
    Args:
        prefix: Prefix for the IDs (e.g., "" for numeric, "SAL-QTN-2024-" for full names)
        start: Start number (inclusive)
        end: End number (inclusive)
    
    Returns:
        List of IDs like ["0752", "0753", ...] or ["SAL-QTN-2024-0752", ...]
    """
    return [f"{prefix}{i:04d}" for i in range(start, end + 1)]


def _normalize_ids(raw_ids: Iterable[str]) -> list[str]:
    """Normalize a list of raw ID strings."""
    return [i.strip() for i in raw_ids if i and i.strip()]


def run_batch_validation(raw_ids: Iterable[str] | None = None) -> dict:
    """
    Batch runner for pipeline validation, intended for finance month-end.

    Usage from bench:
      bench --site <site> execute raven_ai_agent.cli.batch_pipeline_validation.run_batch_validation

    Args:
        raw_ids: Optional list of Quotation/SO IDs to validate. 
                 If None, uses DEFAULT_IDS.

    Returns:
        Dict with ids processed and output file paths.
    """
    ids = _normalize_ids(raw_ids or DEFAULT_IDS)

    app_path = Path(frappe.get_app_path("raven_ai_agent"))
    out_dir = app_path / "transcripts"
    out_dir.mkdir(exist_ok=True)

    ts = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    json_path = out_dir / f"batch_pipeline_{ts}.json"
    md_path = out_dir / f"batch_pipeline_{ts}.md"

    records: list[dict] = []
    md_lines: list[str] = []

    md_lines.append(f"# Batch Pipeline Validation ({ts})")
    md_lines.append("")
    md_lines.append("This report was generated by Raven batch pipeline validation.")
    md_lines.append("")
    md_lines.append("## Summary")
    md_lines.append("")
    md_lines.append(f"- Total IDs processed: {len(ids)}")
    md_lines.append("")

    for raw_id in ids:
        try:
            result = validate_pipeline(raw_id)
            status = "ok"
            error = None
        except Exception as exc:
            # We still want the batch to continue if one ID fails
            result = f"ERROR: {exc}"
            status = "error"
            error = str(exc)

        rec = {
            "input": raw_id,
            "status": status,
            "error": error,
            "output": result,
        }
        records.append(rec)

        md_lines.append(f"## {raw_id}")
        md_lines.append("")
        md_lines.append(result if isinstance(result, str) else str(result))
        md_lines.append("")
        md_lines.append("---")
        md_lines.append("")

    # Write output files
    json_path.write_text(frappe.as_json(records, indent=2), encoding="utf-8")
    md_path.write_text("\n".join(md_lines), encoding="utf-8")

    print(f"Wrote JSON batch report to: {json_path}")
    print(f"Wrote Markdown batch report to: {md_path}")

    return {
        "ids": ids,
        "json_path": str(json_path),
        "md_path": str(md_path),
    }


def main():
    """Entry point for bench execute."""
    return run_batch_validation()


if __name__ == "__main__":
    main()
